### ISSUE TITLE
bolt secret createkeys fails with uninitialized constant

### ISSUE THREAD

**Issue by rogfut** [puppetlabs/puppetlabs-pkcs7#2]
## Describe the Bug
when running `bolt secret createkeys` an error is thrown:

```
uninitialized constant PKCS7CreateKeys::FileUtils
Did you mean?  FileTest
```

## Expected Behavior
the command should create PKCS7 keys at keys/public_key.pkcs7.pem and keys/private_key.pkcs7.pem

## Steps to Reproduce
run `bolt secret createkeys`

view the error

```
uninitialized constant PKCS7CreateKeys::FileUtils
Did you mean?  FileTest
```

## Environment
 - Bolt version 2.8.0
 - puppetlabs-pkcs7 version 0.1.0
 - Windows 10.0.17763

## Additional Context
I also installed bolt version 2.8.0 on Win 10 WSL (ubuntu) and got the same failure.

I managed to fix the bug by adding `require 'fileutils'` to secret_createkeys.rb

**Comment by lucywyman** [comment]
Closed by #5
